name: Deploy to Feuerware FTP

on:
  push:
    branches:
      - main
      - qa
      - dev
  workflow_dispatch:

jobs:
  deploy:
    name: FTP Deploy (${{ github.ref_name }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Determine Server Directory
        id: set-dir
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "dir=/2025/capsulu/" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref_name }}" = "qa" ]; then
            echo "dir=/2025/capsulu/qa/" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref_name }}" = "dev" ]; then
            echo "dir=/2025/capsulu/dev/" >> $GITHUB_OUTPUT
          else
            echo "dir=/2025/capsulu/${{ github.ref_name }}/" >> $GITHUB_OUTPUT
          fi

      - name: FTP Deploy Web App
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./web/"
          server-dir: ${{ steps.set-dir.outputs.dir }}
          exclude: |
            export/**
            downloads/**
            **/.DS_Store
            **/.*
